spring:
  datasource:
    username: root
    password: Root!!2019
    url: jdbc:mysql://47.106.227.129:3306/crm?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B2
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
server:
  port: 80

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
